In [1]:
import torch
print(torch.__version__)

2.5.1+cpu


# Scalar 
A tensor with dimension 0 is called scalar

In [2]:
scalar=torch.tensor(2)
print(scalar)
print(f"dimesnion of this tensor is {scalar.ndim}")

tensor(2)
dimesnion of this tensor is 0


# Vector
A Tensor with dimesnion 1 is called vector

In [3]:
vector= torch.tensor([0,1])
print(vector)
print(f"dimesnion of this tensor is {vector.ndim}")

tensor([0, 1])
dimesnion of this tensor is 1


In [4]:
matrix= torch.tensor([[0,1],
                      [1,2]])
print(matrix)
print(f"dimesnion of this tensor is {matrix.ndim}")

tensor([[0, 1],
        [1, 2]])
dimesnion of this tensor is 2


# Tensor
Anything bigger than 2 dimesnion is called Tensor

In [5]:
tensor=torch.tensor([[[0,1],
                      [1,2],
                      [2,3]]])
print(tensor)
print(f"Dimensio of this tensor is {tensor.ndim}")

tensor([[[0, 1],
         [1, 2],
         [2, 3]]])
Dimensio of this tensor is 3


In [6]:
print(tensor.shape)

torch.Size([1, 3, 2])


# Indexing

In [7]:
print(tensor)
print(tensor[0])
print(tensor[0][0])
print(tensor[0][1])
print(tensor[0][2])
print(tensor[0][2][1])
print(tensor[:,:,0])

tensor([[[0, 1],
         [1, 2],
         [2, 3]]])
tensor([[0, 1],
        [1, 2],
        [2, 3]])
tensor([0, 1])
tensor([1, 2])
tensor([2, 3])
tensor(3)
tensor([[0, 1, 2]])


# Random Tensor

In [8]:
random_tensor=torch.rand(size=(3,4))
print(random_tensor)
print(random_tensor.ndim)
print(random_tensor.shape)

tensor([[0.8721, 0.6991, 0.8277, 0.1086],
        [0.8303, 0.7531, 0.6888, 0.2252],
        [0.0724, 0.5489, 0.8643, 0.9825]])
2
torch.Size([3, 4])


# Application of Random Tensor
Random tensor are widely used in random weight initialization

In [9]:
#Example
input=30
hidden=100
weight_tensor=torch.rand(size=(input,hidden))
print(weight_tensor)
print(weight_tensor.ndim)
print(weight_tensor.shape)

tensor([[0.1148, 0.1402, 0.9876,  ..., 0.6531, 0.8694, 0.9500],
        [0.6819, 0.2321, 0.1435,  ..., 0.0937, 0.9508, 0.9896],
        [0.8035, 0.0516, 0.1112,  ..., 0.6823, 0.6882, 0.3882],
        ...,
        [0.9515, 0.4460, 0.1911,  ..., 0.8637, 0.1401, 0.1746],
        [0.9512, 0.9889, 0.0868,  ..., 0.3731, 0.4467, 0.9554],
        [0.5353, 0.1556, 0.4205,  ..., 0.2667, 0.8900, 0.0442]])
2
torch.Size([30, 100])


In [10]:
#Example of random image creation
random_image_tensor=torch.rand(size=(150,150,3))
import cv2
#cv2.imshow("Window Name", random_image_tensor) #error because opencv takes only numpy tensor as input
#convert this torch tensor to numpy tensor
random_image_np=random_image_tensor.numpy()
cv2.imshow("Window Name", random_image_np)
cv2.waitKey(0)  # Wait until a key is pressed
cv2.destroyAllWindows()  # Close the window

In [20]:
#Example of random image creation
random_image_tensor=torch.rand(size=(150,150,3))
import cv2
#cv2.imshow("Window Name", random_image_tensor) #error because opencv takes only numpy tensor as input
#convert this torch tensor to numpy tensor
random_image_np=random_image_tensor.numpy()*500
cv2.imshow("Window Name", random_image_np)
cv2.waitKey(0)  # Wait until a key is pressed
cv2.destroyAllWindows()  # Close the window

# Zero tensor

In [13]:
zeros=torch.zeros(size=(3,4))
print(zeros.shape)
print(zeros)

torch.Size([3, 4])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


# Ones

In [14]:
ones=torch.ones(size=(3,4))
print(ones.ndim)
print(ones.shape)
print(ones)
print(type(zeros[0][0]))

2
torch.Size([3, 4])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
<class 'torch.Tensor'>


# arange function

In [15]:
range=torch.arange(start=0,end=10)
print(range)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [17]:
range_=torch.arange(start=0,end=10, step=2)
print(range_)
print(range_.tolist())

tensor([0, 2, 4, 6, 8])
[0, 2, 4, 6, 8]


# Dummy image creation using zeros_like function

In [25]:
dummy_image_zeros=torch.zeros_like(input=random_image_tensor)
dummy_image_zeros_np=dummy_image_zeros.numpy()
cv2.imshow("dummy Image", dummy_image_zeros_np)
cv2.waitKey(0)  # Wait until a key is pressed
cv2.destroyAllWindows()  # Close the window

# Dummy image creation using ones_like function

In [27]:
dummy_image_ones=torch.ones_like(input=random_image_tensor)
dummy_image_ones_np=dummy_image_zeros.numpy()
cv2.imshow("dummy Image", dummy_image_zeros_np)
cv2.waitKey(0)  # Wait until a key is pressed
cv2.destroyAllWindows()  # Close the window

# Tensor Manipulation

In [34]:
tensor_t=torch.tensor([1,2,3,4,5])

In [35]:
##  Addition
print(tensor_t+10) #immutable
print(tensor_t)
#or
print(torch.add(tensor_t,10)) #immutable
print(tensor_t)

tensor([11, 12, 13, 14, 15])
tensor([1, 2, 3, 4, 5])
tensor([11, 12, 13, 14, 15])
tensor([1, 2, 3, 4, 5])


In [37]:
##  Substraction
print(tensor_t-10) #immutable
print(tensor_t)
#or
print(torch.sub(tensor_t,10)) #immutable
print(tensor_t)

tensor([-9, -8, -7, -6, -5])
tensor([1, 2, 3, 4, 5])
tensor([-9, -8, -7, -6, -5])
tensor([1, 2, 3, 4, 5])


In [39]:
##  multiplication
print(tensor_t*10) #immutable
print(tensor_t)
#or
print(torch.mul(tensor_t,10)) #immutable
print(tensor_t)

tensor([10, 20, 30, 40, 50])
tensor([1, 2, 3, 4, 5])
tensor([10, 20, 30, 40, 50])
tensor([1, 2, 3, 4, 5])


In [40]:
##  Division
print(tensor_t/10) #immutable
print(tensor_t)
#or
print(torch.div(tensor_t,10)) #immutable
print(tensor_t)

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000])
tensor([1, 2, 3, 4, 5])
tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000])
tensor([1, 2, 3, 4, 5])


# Tensor with Tensor Multiplication, Element Wise

In [43]:
print(tensor_t)
print(tensor_t*tensor_t)

tensor([1, 2, 3, 4, 5])
tensor([ 1,  4,  9, 16, 25])


# Dot Product or Matrix Multiplication

In [51]:
tensor_a=torch.tensor([[1,2],
                       [2,3],
                       [3,4]])
tensor_b=torch.tensor([[1,2],
                       [2,3],
                       [3,4]])
print(tensor_a.shape)
print(tensor_b.shape)
#take the transpose of first tensor
print(torch.matmul(tensor_a,tensor_b.T))

torch.Size([3, 2])
torch.Size([3, 2])
tensor([[ 5,  8, 11],
        [ 8, 13, 18],
        [11, 18, 25]])


# Aggregation

In [62]:
torch_agg=torch.tensor([1,2,3,4,100,300,400,-100])
print(f"minimum value in this tensor{torch_agg.min()}")
print(f"maxiimum value in this tensor{torch_agg.max()}")
print(f"mean value in this tensor {torch_agg.float().mean()}")

minimum value in this tensor-100
maxiimum value in this tensor400
mean value in this tensor 88.75
